# Generated by Django 5.2.4 on 2025-09-02 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_task_is_completed_task_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_invoice_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='stripe_invoice_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='api.project'),
        ),
    ]
