FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# psycopg deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq5 libpq-dev build-essential \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# copy backend code
COPY . /app

EXPOSE 8000